spring:
  datasource:
#    serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://127.0.0.1:3306/lx?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&userSSL=false
    url: jdbc:mysql://127.0.0.1:3306/lx?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      enable: true #开启连接池
      aop-patterns: com.xinxin.controller.*
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-username: xinxin
        login-password: xinxin
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
        wall:
          enabled: true
          config:
            drop-table-allow: false
stu:
  name: 6666
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
